version: "3.8"
services:
  admin-back:
    build: ./

    ports:
      - 8000:8000
    networks:
      - dev-admin
    volumes:
      - .:/var/www/html/
  db:
    image: postgres
  #  restart: always
    ports:
      - '15432:15432'
    environment:
      POSTGRES_PASSWORD: uvi
      POSTGRES_USER: uvi
      POSTGRES_DATABASE: backend_admin
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./build_conf/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
    networks:
      - dev-admin

networks:
  dev-admin:
    driver: bridge
    ipam:
      config:
        - subnet: 172.42.0.0/16
          gateway: 172.42.0.1
volumes:
  postgres_data:

