version: '3.3'

services:
    php:
        build:
            context: docker/local/php/
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP:-1000}'
        ports:
            - '8000:8000'
            - '9006:9006'
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        volumes:
            - .:/var/www:delegated
        environment:
            XDEBUG_CONFIG: '${XDEBUG_CONFIG}'
    cli:
        build:
            context: docker/local/cli/
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP:-1000}'
        volumes:
            - .:/var/www:delegated
    db:
        image: postgres
        restart: always
        ports:
            - '5432:5432'
        environment:
            POSTGRES_PASSWORD: uvi
            POSTGRES_USER: uvi
            POSTGRES_DATABASE: core
            PGDATA: "/var/lib/postgresql/data/pgdata"
        volumes:
            - ./docker/local/db/init.sql:/docker-entrypoint-initdb.d/init.sql
            - postgres_data:/var/lib/postgresql/data
    redis:
        image: redis:latest
        command: >
            --requirepass 123456
        ports:
            - '6379:6379'
        volumes:
            - redis_data:/data
    minio:
        image: "minio/minio:latest"
        command: server /data
        volumes:
            - minio_data:/data
        environment:
            - MINIO_ACCESS_KEY=minio_access_key
            - MINIO_SECRET_KEY=minio_secret_key
        ports:
            - "9080:9000"
            - "9081:9001"
    network_manager:
        build:
            context: docker/local/network_manager
            dockerfile: Dockerfile
        environment:
            SSH_USER: ${SSH_USER}
        volumes:
            - "${HOME}/.ssh/${SSH_USER}:/root/.ssh/id_rsa"
    rabbitmq:
        image: rabbitmq:3.12.1-management
        restart: always
        environment:
            - RABBITMQ_DEFAULT_USER=rmq
            - RABBITMQ_DEFAULT_PASS=rmq
            - RABBITMQ_DEFAULT_VHOST=/
        ports:
            - '15672:15672'
            - '5672:5672'
    opensearch:
        image: opensearchproject/opensearch:latest
        environment:
            - cluster.name=opensearch.cluster
            - node.name=opensearch
            - discovery.type=single-node
            - bootstrap.memory_lock=true
            - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
            - "DISABLE_INSTALL_DEMO_CONFIG=true"
            - "DISABLE_SECURITY_PLUGIN=true"
        ports:
            - 9600:9600
            - 9200:9200
    opensearch-dashboards:
        restart: always
        image: opensearchproject/opensearch-dashboards:latest
        environment:
            - 'OPENSEARCH_HOSTS=["http://opensearch:9200"]'
            - "DISABLE_SECURITY_DASHBOARDS_PLUGIN=true"
        ports:
            - 5601:5601
        expose:
            - "5602"
    pgadmin4:
        image: dpage/pgadmin4:latest
        container_name: pgadmin
        restart: always
        ports:
            - "8081:80"
        environment:
            PGADMIN_DEFAULT_EMAIL: aperevalov@ves-media.com
            PGADMIN_DEFAULT_PASSWORD: gjgfgcf14
        volumes:
            - pgadmin-data:/var/lib/pgadmin
volumes:
    postgres_data:
    redis_data:
    minio_data:
    rabbitmq_data:
    pgadmin-data:
