version: "3.8"
services:
  admin-back:
    build: ./
    ports:
      - '9000:9000'
    networks:
      - dev-admin
networks:
  dev-admin:
    driver: bridge
    ipam:
      config:
        - subnet: 172.42.0.0/16
          gateway: 172.42.0.1
