core:
  appName: core
  image:
    name: "10.0.0.239:80/uvi/core/core"
    tag: "latest"
  replicas: 1
  host: "core.uvi.ru"

import:
  appName: import
  image:
    name: "10.0.0.239:80/uvi/core/import"
    tag: "latest"
  replicas: 1

redis:
  appName: redis
  storageClassName: "cephfs"
  storage: 1Gi

jobs:
  image:
    name: "10.0.0.239:80/uvi/core/job"
    tag: "latest"
  backOffLimit: 1

production: ""
