#!/usr/bin/env bash

MONOLITH_IP=92.246.150.10

if [ ! -d "/${HOME}/.ssh/" ]; then
    mkdir "/${HOME}/.ssh"
fi

if [ ! -f "${HOME}/.ssh/known_hosts" ] || ! grep "${MONOLITH_IP}" "${HOME}/.ssh/known_hosts"; then
    ssh-keyscan 92.246.150.10 >> "${HOME}/.ssh/known_hosts"
fi

ssh -4 -NL 0.0.0.0:3306:127.0.0.1:3306 "${SSH_USER}@${MONOLITH_IP}"
