apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.swagger.appName }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.swagger.appName }}
  ports:
    - protocol: TCP
      port: {{ .Values.swagger.port }}
      targetPort: 80
