.build_image:
  image: docker:latest
  stage: build
  variables:
    DOCKER_TLS_CERTDIR: "/etc/ssl/certs"
  services:
    - name: docker:dind
      command:
        [
          '--insecure-registry=10.0.0.239:80'
        ]
  before_script:
    - docker login ${REGISTRY_URL} -u ${REGISTRY_USER} -p ${REGISTRY_TOKEN}
  script:
    - IMAGE_NAME=${REGISTRY_URL}/uvi/admin/back
    - docker build
        --no-cache
        -t ${IMAGE_NAME}:${CI_COMMIT_SHORT_SHA}
        -t ${IMAGE_NAME}:latest
        -f ./docker/${DOCKERFILE_PATH}/Dockerfile
        .
    - docker push ${IMAGE_NAME}:${CI_COMMIT_SHORT_SHA}
    - docker push ${IMAGE_NAME}:latest

#.build_swagger:
#  image: ${REGISTRY_URL}/uvi/core:latest
#  stage: build
#  artifacts:
#    paths:
#      - .openapi-${CI_COMMIT_SHORT_SHA}.yaml
#  before_script:
#    - composer install --no-scripts
#  script:
#    - php vendor/bin/openapi app -o .openapi-${CI_COMMIT_SHORT_SHA}.yaml
